<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>DWG2SVGConverter</RootNamespace>
    <AssemblyName>DWG2SVGConverter</AssemblyName>
  </PropertyGroup>
</Project>